### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by avaisa** [libragen/felix#12]
go get: github.com/libragen/felix@v0.0.0-20190909151554-2ce64594c3a4: parsing go.mod:
        module declares its path as: github.com/dejavuzhou/felix
                but was required as: github.com/libragen/felix

**Comment by mojocn** [comment]
my repo was rename from `github.com/dejavuzhou/felix` to `github.com/libragen/felix`

so replace `/dejavuzhou/` to `libragen/`
