### ISSUE TITLE
找不到config

### ISSUE THREAD

**Issue by GuiBin2013** [libragen/felix#13]
看了一下readme，感觉像是要自己配个config ?
我用docker(golang:1.13)直接按照编译和运行的流程后，执行felix sshw出现：

FATA[0000] Fatal error config file: Config File "config" Not Found in "[/go/src/github.com/libragen/felix /etc/felix /root/.felix]"

是程序出错了还是需要自己配个config还是？
如果需要配置个config，能否直接提供一份default config在代码中，一开始要额外编辑，对docker玩家有点难受呀。

**Comment by mojocn** [comment]
https://github.com/libragen/felix#demo-configtoml-file       把config.toml 文件放在 ~  /etc/felix/ 或者二进制同一个目录中

**Comment by mojocn** [comment]
https://github.com/libragen/felix/blob/master/cmd/root.go  最后几行代码    https://mojotv.cn/2018/12/26/how-to-use-viper-configuration-in-golang
